# Streamlit Secrets Configuration
# Copy this file and add your actual API key
# This file should NOT be committed to GitHub

CENSUS_API_KEY = "7f126e5d8766f67cd459a5a6da054dacd0977255"

# To get a free Census Bureau API key:
# 1. Visit: https://api.census.gov/data/key_signup.html
# 2. Fill out the form
# 3. Check your email for the API key
# 4. Replace "your_census_api_key_here" with your actual key